name: Metrics Repository Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight (UTC)

jobs:
  metrics:
    runs-on: ubuntu-latest
    concurrency:
      group: repo-stats-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Generate repository metrics
        uses: lowlighter/metrics@latest
        with:
          template: repository
          filename: metrics.repository.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: nick2bad4u
          repo: FitFileViewer
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          commits_authoring: nick2bad4u
          config_display: large
          config_octicon: yes
          config_timezone: America/Detroit
          config_twemoji: yes
          plugin_followup: yes
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 30
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_indepth: yes
          plugin_languages_limit: 20
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines_history_limit: 20
          plugin_lines_repositories_limit: 8
          plugin_lines_sections: base
          plugin_repositories: yes
          plugin_repositories_order: featured, pinned, starred, random
          repositories_forks: yes
